language: node_js
node_js:
  - 10
cache: npm
install:
  - npm ci
jobs:
  include:
    - stage: Demo app production build
      script: npm run build:prod
    - stage: Build module
      script:
        - cd src/shared/modules/badgeup-client
        - npm ci
        - npm run build-module
        - npm run check-module
