dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
git:
  depth: 1
addons:
  chrome: stable
jobs:
  include:
    - stage: test
      script: npm run lint
      script: npm run test-ci
stages:
  - test
